require 'user.plugins'
require 'user.treesitter'
require 'user.gitsigns'
require 'user.illuminate'
require 'user.surround'
require 'user.autopairs'
require 'user.ibl'
require 'user.neo-tree'

require 'user.options'
require 'user.colorscheme'
require 'user.keymaps'
