require 'user.options'
require 'user.plugins'
require 'user.colorscheme'
require 'user.treesitter'
require 'user.indent-line'
require 'user.nvim-tree'
require 'user.bufferline'
require 'user.telescope'

require 'user.autocommands'
require 'user.keymaps'
